# Generated by Django 2.0.7 on 2018-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20180814_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_hourly',
            field=models.IntegerField(),
        ),
    ]
