# Generated by Django 2.0.7 on 2018-08-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='approval',
            new_name='approved',
        ),
    ]
