# Generated by Django 2.0.7 on 2018-09-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
